services:
  opensearch:
    image: opensearchproject/opensearch:latest
    environment:
      - discovery.type=single-node
      - "OPENSEARCH_INITIAL_ADMIN_PASSWORD=admin"
    ports:
      - "9200:9200"
      - "9600:9600"
    networks:
      - opensearch-net

  app:
    build: .
    environment:
      - OPENSEARCH_HOST=http://opensearch:9200
    volumes:
      - ./:/app
    expose:
      - 9000
    depends_on:
      - opensearch
    networks:
      - opensearch-net

  web:
    image: nginx:latest
    ports:
      - 8001:8001
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./index.html:/var/www/html/index.html
      - ./scripts:/var/www/html/scripts
      - ./styles:/var/www/html/styles
      - ./components:/var/www/html/components
      - ./assets:/var/www/html/assets
    depends_on:
      - app
    networks:
      - opensearch-net

networks:
  opensearch-net:
    driver: bridge
