services:
  opensearch:
    image: opensearchproject/opensearch:latest
    environment:
      - discovery.type=single-node
      - OPENSEARCH_INITIAL_ADMIN_PASSWORD=${ADMIN_PASSWORD}
    ports:
      - 9200:9200
      - 9600:9600
    networks:
      - opensearch-net

  app:
    build: .
    environment:
      - OPENSEARCH_HOST=http://opensearch:9200
    volumes:
      - ./:/app
    expose:
      - 9000
    depends_on:
      - opensearch
    networks:
      - opensearch-net

  web:
    image: nginx:latest
    ports:
      - 8001:8001
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./frontend/index.html:/var/www/html/index.html
      - ./frontend/scripts:/var/www/html/scripts
      - ./frontend/styles:/var/www/html/styles
      - ./frontend/components:/var/www/html/components
      - ./frontend/assets:/var/www/html/assets
    depends_on:
      - app
    networks:
      - opensearch-net

networks:
  opensearch-net:
    driver: bridge
