services:
  opensearch:
    image: opensearchproject/opensearch:latest
    container_name: opensearch
    environment:
      - discovery.type=single-node
      - "OPENSEARCH_INITIAL_ADMIN_USER=${ADMIN_USER}"
      - "OPENSEARCH_INITIAL_ADMIN_PASSWORD=${ADMIN_PASSWORD}"
      - "DISABLE_SECURITY_PLUGIN=true"
    ports:
      - "9200:9200"
      - "9600:9600"
    networks:
      - opensearch-net

  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:latest
    container_name: opensearch-dashboards
    ports:
      - "5601:5601"
    environment:
      - "OPENSEARCH_HOSTS=http://opensearch:9200"
      - "DISABLE_SECURITY_PLUGIN=true"
      - "OPENSEARCH_USERNAME=${ADMIN_USER}"
      - "OPENSEARCH_PASSWORD=${ADMIN_PASSWORD}"
    networks:
      - opensearch-net
    depends_on:
      - opensearch
  
  app:
    build: .
    environment:
      - OPENSEARCH_HOST=http://opensearch:9200
    volumes:
      - ./:/app
    expose:
      - 9000
    depends_on:
      - opensearch
    networks:
      - opensearch-net

  web:
    image: nginx:latest
    ports:
      - 8001:8001
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./index.html:/var/www/html/index.html
      - ./scripts:/var/www/html/scripts
      - ./styles:/var/www/html/styles
      - ./components:/var/www/html/components
      - ./assets:/var/www/html/assets
    depends_on:
      - app
    networks:
      - opensearch-net

networks:
  opensearch-net:
    driver: bridge
